### ISSUE TITLE
Remove populationSize: from DSL

### ISSUE THREAD

**Issue by SergeStinckwich** [UNU-Macau/kendrick#113]
A previous issue #73 remove all code for explicitly give a size to a new population.
``KEPopulation>>size:`` is still to be removed but is used the DSL in populationSize:
We should apply the DRY approach on the DSL than the Kendrick meta-model, i.e don't repeat population size many time.
Example :

```Smalltalk
Scenario MeaslesPopulation
    on: 'Measles';
    populationSize: 100000;
    S: 99999;
    I: 1;
    others: 0.
```

Instead we will use the following syntax:
```Smalltalk
Scenario MeaslesPopulation
    on: 'Measles';
    S: 99999;
    I: 1;
    others: 0.
```

**Comment by YvanGuifo** [comment]
I removed the user examples of this populationSize method: in the DSL
