### ISSUE TITLE
Switch from Roassal2 to Roassal3 for plot visualisations

### ISSUE THREAD

**Issue by SergeStinckwich** [UNU-Macau/kendrick#126]
Use Roassal3 (https://github.com/ObjectProfile/Roassal3) instead of Roassal2 for plotting results of simulation, because plot support is much more elaborate on Roassal3 than Roassal2 and this possible to do log and log-log plots also more easily.

**Comment by SergeStinckwich** [comment]
Add Roassal3 baseline to ease the transition.

**Comment by SergeStinckwich** [comment]
We are able to plot results of simulation with Roassal3. What is missing is log/log-log plots and visualisation of SANs graph.

**Comment by SergeStinckwich** [comment]
Normally log plots are possible with Roassal3: https://github.com/ObjectProfile/Roassal3/issues/92

**Comment by SergeStinckwich** [comment]
KEChart has been introduced for the plots with Roassal3. All users of the previous classes (KEDiagramBuilder and subclasses) should use KEChart now.

**Comment by YvanGuifo** [comment]
Use of KEChart for plots. This is the migration from roassal2 to roassal3 [https://github.com/UNU-Macau/kendrick/pull/260](https://github.com/UNU-Macau/kendrick/pull/260)

**Comment by SergeStinckwich** [comment]
Done.
