### ISSUE TITLE
extends: is not really extending model

### ISSUE THREAD

**Issue by SergeStinckwich** [UNU-Macau/kendrick#129]
When someone do:
```Smalltalk
c2:= KEModelPart extends: c1.
```

we don't extend ``c1`` to build ``c2``, we just copy ``c1`` to produce a new model ``c2``.

We should rename ``extends:`` as ``copy`` and use it like that:

```Smalltalk
c2 := c1 copy.
```

**Comment by YvanGuifo** [comment]
I just changed the extends method to the copy method and also modified some examples that used extends

**Comment by SergeStinckwich** [comment]
Can we close issues only when PR has been merged ?

**Comment by YvanGuifo** [comment]
But can be reassuring to close once the PR is approved
