### ISSUE TITLE
Methods buildFromCompartments: and buildFromCompartments:cardinalities: have non-uniform parameters

### ISSUE THREAD

**Issue by SergeStinckwich** [UNU-Macau/kendrick#22]
Compare the two following examples:

``` Smalltalk
model := KEModel new.
model buildFromCompartments: 
        {(#species->#(#Mosquito #Reservoir1 #Reservoir2)). (#status->#(#S #I #R))}
cardinalities: #(9999 1 0 999 1 0 1999 1 0).
```

and 

``` Smalltalk
model := KEModel new.
model buildFromCompartments: '{
    { #status: #S, #species: #mosquito }: 9999,
    { #status: #I, #species: #mosquito }: 1,
    { #status: #R, #species: #mosquito }: 0,
    { #status: #S, #species: #reservoir1 }: 999,
    { #status: #I, #species: #reservoir1 }: 1,
    { #status: #R, #species: #reservoir1 }: 0,
    { #status: #S, #species: #reservoir2 }: 1999,
    { #status: #I, #species: #reservoir2 }: 1,
    { #status: #R, #species: #reservoir2 }: 0
    }'.
```

Why using an array of association in the first case and a STON structure in the second case ? This is surprising for an end user I guess.

My hypothesis is that the first one is cartesian product of species \* status and the one an exhaustive list of compartiments with cardinalities. Can we propose a clever and more uniform syntax ?

**Comment by btmanh** [comment]
I think that the second one is clear but it can become so long when the number of attributes or the value of each attribute increase. So i created the first method for shortness.
I am always concerned with initializing compartments but i have not found a clever and more uniform syntax yet.

**Comment by SergeStinckwich** [comment]
I could not find this method anymore in the current code. I guess its has been removed.
