### ISSUE TITLE
Be able to generate a PNG file from a visualisation

### ISSUE THREAD

**Issue by SergeStinckwich** [UNU-Macau/kendrick#272]
It was possible before with DSL in Roassal2, but this does not work anymore with the move to R3.
Method ``Visualization>>exportToPng`` need to be fixed.

**Comment by YvanGuifo** [comment]
In the current documentation of Roassal3 it seems not to have export in PNG format

**Comment by SergeStinckwich** [comment]
Yes this is why I add the dependency to: https://github.com/ObjectProfile/Roassal3Exporters

**Comment by SergeStinckwich** [comment]
close by #301
