### ISSUE TITLE
Change values in TensorTest >> testGetPosition

### ISSUE THREAD

**Issue by khinsen** [UNU-Macau/kendrick#360]
In both `t1` and `t2`, each element's position equals its value. That makes `getPosition:` look like a synonym for `get:`.

**Comment by SergeStinckwich** [comment]
Thank you for your comment Konrad. I think this is better to interact directly on Yvan's PR in the Polymath repository instead of here: https://github.com/PolyMathOrg/PolyMath/pull/210
